version: '3'
services: 
    calculator_service:
        build: ./
        volumes: 
            - ./:/usr/src/app/
        ports: 
            - 5000:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1
